eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 9000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 9000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1


hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000 #断路器超时时间，默认1000ms

feign:
 hystrix:
  enabled: true

server:
  port: 8763
  max-http-header-size: 404857600
  tomcat:
    max-http-post-size: 404857600


spring:
  #mongodb配置
  data:
    mongodb:
      #uri: mongodb://39.98.68.212:27017/test
      uri: mongodb://fetxdmin:ZYLb2fTT@39.100.254.13:27017/admin
      #        uri: mongodb://127.0.0.1:27017/admin
  application:
    name: b2bSearch
  cloud:
    discovery:
      enabled: true
    config:
      uri: http://localhost:${config.port:8762}
      profile: ${config.profile:dev}
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 39.100.254.13
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: redis@fetxCtripApi
    # 连接超时时间（毫秒）
    timeout: 600000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 8
  #logback日志配置
    output:
      ansi:
        #控制台开启彩色日志显示
        enabled: DETECT

IsReleaseEnv: false

logging:
    #设置各包下的日志等级
    level:
        com:
          fntx:
            search:
                controller: INFO
                mapper: INFO
                service: INFO
                model: INFO
    #日志导出到文件  名为logback   路径为当前项目下的相对路径
    file: log/b2bSearch.log