server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false    #默认true，单机环境设置为false，表示不向注册中心注册自己
    fetchRegistry: false         #默认true，单机环境设置为false，表示不需要向注册中心检索自己
    serviceUrl:
      defaultZone: http://127.0.0.1:8700/eureka/
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 10000
#监控中心相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"       #过滤监控中心能监控的项目
  endpoint:
    health:
      show-details: ALWAYS #管理端点健康状况显示详细信息